# Generated by Django 2.2 on 2020-07-09 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_codice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codice',
            name='id',
        ),
        migrations.AddField(
            model_name='codice',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SocialCodice',
            fields=[
                ('image_qr', models.ImageField(upload_to='')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('social_slug', models.SlugField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_qrs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'socialcodice',
                'verbose_name_plural': 'socialcodici',
            },
        ),
    ]
