# Generated by Django 2.2 on 2020-07-09 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200709_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codice',
            name='image_qr',
            field=models.FileField(upload_to='static/img', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
        migrations.AlterField(
            model_name='socialcodice',
            name='image_qr',
            field=models.FileField(upload_to='static/img', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
