# Generated by Django 2.2 on 2020-07-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200709_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='codice',
            name='date_creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialcodice',
            name='date_creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
