# Generated by Django 2.2 on 2020-07-19 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200709_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialcodice',
            options={'verbose_name': 'SocialCodice', 'verbose_name_plural': 'SocialCodici'},
        ),
    ]
