# Generated by Django 2.2 on 2020-07-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200719_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='codice',
            name='bought',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='socialcodice',
            name='bought',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
