# Generated by Django 2.2 on 2020-07-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200720_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichiestaAiuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField(max_length=700)),
                ('solved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'RichiestaAiuto',
                'verbose_name_plural': 'RichiesteAiuto',
            },
        ),
    ]
