# Generated by Django 2.2 on 2020-07-24 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_richiestaaiuto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='richiestaaiuto',
            name='email',
        ),
        migrations.AddField(
            model_name='richiestaaiuto',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
