# Generated by Django 3.0.8 on 2020-08-05 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20200724_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codice',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='qrs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialcodice',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_qrs', to=settings.AUTH_USER_MODEL),
        ),
    ]
